dcp: include grp.h and correct type of gids
The use of setgroups() requires including <grp.h>.

Fixes warning:

	src/dcp/dcp.c:416:13: warning: implicit declaration of function ‘setgroups’; did you mean ‘getgroups’? [-Wimplicit-function-declaration]
	  416 |         if (setgroups(0, NULL) < 0) {
	      |             ^~~~~~~~~
	      |             getgroups
	[ 50%] Linking C executable dcp

gids[MAX_GIDS] is used by getgroups().  The second argument should be of type gid_t *.

Fixes warning:

	src/dcp/dcp.c:407:42: warning: passing argument 2 of ‘getgroups’ from incompatible pointer type [-Wincompatible-pointer-types]
	  407 |         gids_count = getgroups(MAX_GIDS, &gids);
	      |                                          ^~~~~
	      |                                          |
	      |                                          uid_t (*)[100] {aka unsigned int (*)[100]}
	In file included from src/dcp/dcp.c:7:
	/usr/include/unistd.h:689:43: note: expected ‘__gid_t *’ {aka ‘unsigned int *’} but argument is of type ‘uid_t (*)[100]’ {aka ‘unsigned int (*)[100]’}
	  689 | extern int getgroups (int __size, __gid_t __list[]) __THROW __wur;

Signed-off-by: Olaf Faaland <faaland1@llnl.gov>